name: flutter_firebase_template
description: A Flutter Application showing how to use Auth and Firestore on the web and mobile.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  after_layout: any
  json_annotation: ^2.4.0
  intl: ^0.15.8
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  build_web_compilers: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0
  json_serializable: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Regular.ttf
          weight: 400
